name: mini_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.3.0
  cloud_firestore: ^4.15.8
  dio: ^5.4.1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.2.0
  permission_handler: ^11.3.1
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  flutter_svg: ^2.0.10+1
  connectivity: ^3.0.3
  flutter_ringtone_player: ^3.0.0
  socket_io_client: ^2.0.3+1
  appflowy_board: ^0.1.0
  kanban_board: ^0.1.0
  dotted_border: ^2.0.0+1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.0
  flutter_webview_plugin: ^0.4.0
  flutter_webrtc: ^0.9.48+hotfix.1
  videosdk: 1.1.8
  flutter_dotenv: ^5.0.2
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.2.3
  lottie: ^2.2.0
  responsive_framework: 1.1.1
  window_manager: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/person1.jpg
    - assets/person2.jpg
    - assets/person3.jpg
    - assets/person4.jpg
    - assets/notyet.png
    - assets/images/login.png
    - assets/
    - .env
